import React, { useState, useEffect } from "react";
import {
  Card,
  Row,
  Col,
  Form,
  Input,
  Select,
  Switch,
  Button,
  List,
  Tag,
  Divider,
  ColorPicker,
  InputNumber,
  Tabs,
  Modal,
  Spin,
  Space,
  Tooltip,
} from "antd";
import {
  PlusOutlined,
  FormOutlined,
  DeleteOutlined,
  ExclamationCircleOutlined,
  SaveOutlined,
  TableOutlined,
  FileWordOutlined,
} from "@ant-design/icons";
import RichTextEditor from "./RichTextEditor";

const { Option } = Select;
const { confirm } = Modal;

const BillingTemplateEditor = ({ templates, onCreate, onUpdate, onDelete }) => {
  const [editingId, setEditingId] = useState(null);
  const [filterType, setFilterType] = useState("ALL");
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();

  // Reset editing state if the selected template is deleted externally
  useEffect(() => {
    if (
      editingId &&
      !templates.find((t) => t.templateId === editingId) &&
      !templates.find((t) => t._id === editingId)
    ) {
      setEditingId(null);
      form.resetFields();
    }
  }, [templates, editingId, form]);

  // Filter Logic
  const filteredTemplates = templates.filter((t) => {
    const type = t.printDetails?.type || t.type;
    return filterType === "ALL" ? true : type === filterType;
  });

  // --- LOAD DATA INTO FORM ---
  const handleEdit = (template) => {
    setEditingId(template._id);

    const formData = {
      ...template,
      ...template.printDetails,
      content: template.printDetails?.content || template.content || {},
    };

    form.setFieldsValue(formData);
  };

  // --- CREATE NEW (Updated with Full Schema Defaults) ---
  const handleCreateClick = async () => {
    setLoading(true);
    const newTemplatePayload = {
      name: "New Template",
      category: "PRINT",
      isDefault: false,
      printDetails: {
        type: "BILL",
        pageSize: "A4",
        orientation: "portrait",
        margins: { top: 10, bottom: 10, left: 10, right: 10 },
        content: {
          accentColor: "#007bff",
          fontFamily: "Roboto",
          showLogo: true,
          showInstitutionDetails: true,
          showQrCode: true,
          headerHtml: "<h1>{{institution.institutionName}}</h1>",
          footerHtml: "<p>Generated by System</p>",

          // --- NEW: Table Structure Defaults from Schema ---
          tableStructure: {
            showHead: true,
            density: "normal",
            striped: false,
            columns: [
              {
                id: "1",
                label: "#",
                dataKey: "index",
                width: "5%",
                align: "center",
                visible: true,
              },
              {
                id: "2",
                label: "Description",
                dataKey: "name",
                width: "55%",
                align: "left",
                visible: true,
              },
              {
                id: "3",
                label: "Qty",
                dataKey: "qty",
                width: "10%",
                align: "center",
                visible: true,
              },
              {
                id: "4",
                label: "Price",
                dataKey: "price",
                width: "15%",
                align: "right",
                visible: true,
              },
              {
                id: "5",
                label: "Amount",
                dataKey: "total",
                width: "15%",
                align: "right",
                visible: true,
              },
            ],
            summarySettings: {
              showTax: true,
              showDiscount: true,
              showDues: true,
              wordsAmount: true,
            },
          },
        },
      },
      commDetails: { triggerEvent: "NONE" },
    };

    const createdTemplate = await onCreate(newTemplatePayload);
    setLoading(false);

    if (createdTemplate) {
      handleEdit(createdTemplate);
    }
  };

  // --- SAVE CHANGES ---
  const handleSaveClick = async () => {
    try {
      const values = await form.validateFields();
      setLoading(true);

      const colorHex =
        typeof values.content?.accentColor === "object"
          ? values.content.accentColor.toHexString()
          : values.content?.accentColor;

      const apiPayload = {
        institutionId: values.institutionId,
        name: values.name,
        category: "PRINT",
        isDefault: values.isDefault || false,
        printDetails: {
          type: values.type,
          pageSize: values.pageSize,
          orientation: values.orientation,
          margins: values.margins,
          content: {
            ...values.content,
            accentColor: colorHex,
          },
        },
      };

      await onUpdate(editingId, apiPayload);
      setLoading(false);
    } catch (error) {
      console.error("Validation Failed:", error);
      setLoading(false);
    }
  };

  const handleDeleteClick = (e, id) => {
    e.stopPropagation();
    confirm({
      title: "Delete Template?",
      icon: <ExclamationCircleOutlined />,
      content: "Are you sure? This cannot be undone.",
      okText: "Yes, Delete",
      okType: "danger",
      onOk() {
        if (editingId === id) {
          setEditingId(null);
          form.resetFields();
        }
        onDelete(id);
      },
    });
  };

  return (
    <Row gutter={24} style={{ height: "100%" }}>
      {/* LEFT SIDEBAR: LIST */}
      <Col
        span={6}
        style={{ borderRight: "1px solid #f0f0f0", minHeight: "75vh" }}
      >
        <div style={{ marginBottom: 16 }}>
          <Button
            block
            type="dashed"
            icon={<PlusOutlined />}
            onClick={handleCreateClick}
            loading={loading}
            style={{ marginBottom: 10 }}
          >
            Create New Template
          </Button>
          <Select
            defaultValue="ALL"
            style={{ width: "100%" }}
            onChange={setFilterType}
          >
            <Option value="ALL">All Types</Option>
            <Option value="BILL">Bills</Option>
            <Option value="LAB_REPORT">Lab Reports</Option>
            <Option value="PRESCRIPTION">Prescriptions</Option>
          </Select>
        </div>
        <List
          dataSource={filteredTemplates}
          renderItem={(item) => {
            const type = item.printDetails?.type || item.type;
            const isSelected = item._id === editingId;
            return (
              <List.Item
                actions={[
                  <Button
                    key="del"
                    type="text"
                    danger
                    size="small"
                    icon={<DeleteOutlined />}
                    onClick={(e) => handleDeleteClick(e, item._id)}
                  />,
                ]}
                style={{
                  background: isSelected ? "#e6f7ff" : "white",
                  border: isSelected
                    ? "1px solid #1890ff"
                    : "1px solid #f0f0f0",
                  padding: "10px",
                  borderRadius: 6,
                  marginBottom: 8,
                  cursor: "pointer",
                }}
                onClick={() => handleEdit(item)}
              >
                <List.Item.Meta
                  title={<span style={{ fontWeight: 500 }}>{item.name}</span>}
                  description={
                    <div style={{ fontSize: 11 }}>
                      <Tag color="blue">{type}</Tag>
                      {item.isDefault && <Tag color="green">Default</Tag>}
                    </div>
                  }
                />
              </List.Item>
            );
          }}
        />
      </Col>

      {/* RIGHT SIDEBAR: EDITOR */}
      <Col span={18}>
        {editingId ? (
          <Form layout="vertical" form={form}>
            {/* HEADER */}
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginBottom: 15,
                borderBottom: "1px solid #eee",
                paddingBottom: 10,
              }}
            >
              <span style={{ fontSize: 16, fontWeight: "bold" }}>
                Editing Template
              </span>
              <Button
                type="primary"
                icon={<SaveOutlined />}
                onClick={handleSaveClick}
                loading={loading}
              >
                Save Changes
              </Button>
            </div>

            {/* Hidden fields */}
            <Form.Item name="institutionId" hidden>
              <Input />
            </Form.Item>
            <Form.Item name="templateId" hidden>
              <Input />
            </Form.Item>

            <Tabs
              defaultActiveKey="settings"
              items={[
                {
                  key: "settings",
                  label: (
                    <span>
                      <FormOutlined /> Page Settings
                    </span>
                  ),
                  children: (
                    <Card size="small">
                      <Row gutter={16}>
                        <Col span={12}>
                          <Form.Item
                            name="name"
                            label="Template Name"
                            rules={[
                              { required: true, message: "Name is required" },
                            ]}
                          >
                            <Input placeholder="e.g. OP Bill Standard" />
                          </Form.Item>
                        </Col>
                        <Col span={12}>
                          <Form.Item name="category" label="Category">
                            <Input disabled defaultValue="PRINT" />
                          </Form.Item>
                        </Col>
                      </Row>
                      <Row gutter={16}>
                        <Col span={8}>
                          <Form.Item
                            name="type"
                            label="Template Type"
                            rules={[{ required: true }]}
                          >
                            <Select>
                              <Option value="BILL">Bill / Invoice</Option>
                              <Option value="LAB_REPORT">Lab Report</Option>
                              <Option value="PRESCRIPTION">Prescription</Option>
                            </Select>
                          </Form.Item>
                        </Col>
                        <Col span={8}>
                          <Form.Item name="pageSize" label="Page Size">
                            <Select>
                              <Option value="A4">A4</Option>
                              <Option value="A5">A5</Option>
                              <Option value="Thermal80mm">
                                Thermal (80mm)
                              </Option>
                            </Select>
                          </Form.Item>
                        </Col>
                        <Col span={8}>
                          <Form.Item name="orientation" label="Orientation">
                            <Select>
                              <Option value="portrait">Portrait</Option>
                              <Option value="landscape">Landscape</Option>
                            </Select>
                          </Form.Item>
                        </Col>
                      </Row>
                      <Row gutter={16}>
                        <Col span={8}>
                          <Form.Item
                            name="isDefault"
                            label="Set as Default"
                            valuePropName="checked"
                          >
                            <Switch />
                          </Form.Item>
                        </Col>
                      </Row>
                      <Divider orientation="left">Margins (mm)</Divider>
                      <Input.Group compact>
                        <Form.Item name={["margins", "top"]} noStyle>
                          <InputNumber
                            style={{ width: "25%" }}
                            placeholder="Top"
                          />
                        </Form.Item>
                        <Form.Item name={["margins", "right"]} noStyle>
                          <InputNumber
                            style={{ width: "25%" }}
                            placeholder="Right"
                          />
                        </Form.Item>
                        <Form.Item name={["margins", "bottom"]} noStyle>
                          <InputNumber
                            style={{ width: "25%" }}
                            placeholder="Bottom"
                          />
                        </Form.Item>
                        <Form.Item name={["margins", "left"]} noStyle>
                          <InputNumber
                            style={{ width: "25%" }}
                            placeholder="Left"
                          />
                        </Form.Item>
                      </Input.Group>
                    </Card>
                  ),
                },
                {
                  key: "design",
                  label: (
                    <span>
                      <FileWordOutlined /> Design Editor
                    </span>
                  ),
                  children: (
                    <div
                      style={{
                        height: "65vh",
                        overflowY: "auto",
                        paddingRight: 10,
                      }}
                    >
                      <Card
                        size="small"
                        title="Header Design"
                        style={{ marginBottom: 16 }}
                      >
                        <Form.Item name={["content", "headerHtml"]} noStyle>
                          <RichTextEditor placeholder="Design your header..." />
                        </Form.Item>
                      </Card>

                      <Card
                        size="small"
                        title="Footer Design"
                        style={{ marginBottom: 16 }}
                      >
                        <Form.Item name={["content", "footerHtml"]} noStyle>
                          <RichTextEditor placeholder="Design your footer..." />
                        </Form.Item>
                      </Card>

                      <Divider>Visual Settings</Divider>
                      <Row gutter={16}>
                        <Col span={8}>
                          <Form.Item
                            name={["content", "accentColor"]}
                            label="Brand Color"
                          >
                            <ColorPicker showText />
                          </Form.Item>
                        </Col>
                        <Col span={8}>
                          <Form.Item
                            name={["content", "fontFamily"]}
                            label="Font"
                          >
                            <Select>
                              <Option value="Roboto">Roboto</Option>
                              <Option value="Open Sans">Open Sans</Option>
                            </Select>
                          </Form.Item>
                        </Col>
                        <Col span={8}>
                          <div
                            style={{
                              paddingTop: 30,
                              display: "flex",
                              gap: 10,
                              flexWrap: "wrap",
                            }}
                          >
                            <Form.Item
                              name={["content", "showLogo"]}
                              valuePropName="checked"
                              noStyle
                            >
                              <Switch
                                checkedChildren="Logo"
                                unCheckedChildren="No Logo"
                              />
                            </Form.Item>
                            <Form.Item
                              name={["content", "showQrCode"]}
                              valuePropName="checked"
                              noStyle
                            >
                              <Switch
                                checkedChildren="QR"
                                unCheckedChildren="No QR"
                              />
                            </Form.Item>
                            <Form.Item
                              name={["content", "showInstitutionDetails"]}
                              valuePropName="checked"
                              noStyle
                            >
                              <Switch
                                checkedChildren="Inst. Info"
                                unCheckedChildren="No Inst. Info"
                              />
                            </Form.Item>
                          </div>
                        </Col>
                      </Row>
                    </div>
                  ),
                },
                {
                  key: "table",
                  label: (
                    <span>
                      <TableOutlined /> Table & Data
                    </span>
                  ),
                  children: (
                    <div
                      style={{
                        height: "65vh",
                        overflowY: "auto",
                        paddingRight: 10,
                      }}
                    >
                      <Card
                        size="small"
                        title="Table Appearance"
                        style={{ marginBottom: 16 }}
                      >
                        <Row gutter={16}>
                          <Col span={8}>
                            <Form.Item
                              name={["content", "tableStructure", "density"]}
                              label="Density"
                            >
                              <Select>
                                <Option value="compact">Compact</Option>
                                <Option value="normal">Normal</Option>
                                <Option value="spacious">Spacious</Option>
                              </Select>
                            </Form.Item>
                          </Col>
                          <Col span={8}>
                            <Form.Item
                              name={["content", "tableStructure", "showHead"]}
                              label="Show Header"
                              valuePropName="checked"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                          <Col span={8}>
                            <Form.Item
                              name={["content", "tableStructure", "striped"]}
                              label="Zebra Stripes"
                              valuePropName="checked"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                        </Row>
                      </Card>

                    <Card size="small" title="Columns Configuration" style={{ marginBottom: 16 }}>
    {/* --- NEW: Header Labels --- */}
    <div style={{ display: 'flex', marginBottom: 5, fontSize: 12, fontWeight: 600, color: '#888' }}>
        <div style={{ width: 44, textAlign: 'center' }}>Show</div>
        <div style={{ width: 150, marginLeft: 8 }}>Column Label</div>
        <div style={{ width: 100, marginLeft: 8 }}>Width</div>
        <div style={{ width: 100, marginLeft: 8 }}>Align</div>
    </div>

    <Form.List name={["content", "tableStructure", "columns"]}>
        {(fields) => (
            <div>
                {fields.map((field) => (
                    <Space key={field.key} style={{ display: 'flex', marginBottom: 8 }} align="center">
                        
                        {/* Hidden IDs (Critical for saving) */}
                        <Form.Item {...field} name={[field.name, 'id']} hidden><Input /></Form.Item>
                        <Form.Item {...field} name={[field.name, 'dataKey']} hidden><Input /></Form.Item>

                        {/* Visibility Switch */}
                        <Tooltip title="Toggle Visibility">
                            <Form.Item
                                {...field}
                                name={[field.name, 'visible']}
                                valuePropName="checked"
                                noStyle
                            >
                                <Switch size="small" />
                            </Form.Item>
                        </Tooltip>

                        {/* Label Input */}
                        <Form.Item
                            {...field}
                            name={[field.name, 'label']}
                            noStyle
                        >
                            <Input placeholder="Label" style={{ width: 150 }} />
                        </Form.Item>

                        {/* Width Input */}
                        <Form.Item
                            {...field}
                            name={[field.name, 'width']}
                            noStyle
                        >
                            <Input placeholder="e.g. 10%" style={{ width: 100 }} />
                        </Form.Item>

                        {/* Alignment Select */}
                        <Form.Item
                            {...field}
                            name={[field.name, 'align']}
                            noStyle
                        >
                            <Select style={{ width: 100 }}>
                                <Option value="left">Left</Option>
                                <Option value="center">Center</Option>
                                <Option value="right">Right</Option>
                            </Select>
                        </Form.Item>
                    </Space>
                ))}
            </div>
        )}
    </Form.List>
</Card>

                      <Card size="small" title="Financial Summary Settings">
                        <Row gutter={16}>
                          <Col span={6}>
                            <Form.Item
                              name={[
                                "content",
                                "tableStructure",
                                "summarySettings",
                                "showTax",
                              ]}
                              valuePropName="checked"
                              label="Tax"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                          <Col span={6}>
                            <Form.Item
                              name={[
                                "content",
                                "tableStructure",
                                "summarySettings",
                                "showDiscount",
                              ]}
                              valuePropName="checked"
                              label="Discount"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                          <Col span={6}>
                            <Form.Item
                              name={[
                                "content",
                                "tableStructure",
                                "summarySettings",
                                "showDues",
                              ]}
                              valuePropName="checked"
                              label="Due Balance"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                          <Col span={6}>
                            <Form.Item
                              name={[
                                "content",
                                "tableStructure",
                                "summarySettings",
                                "wordsAmount",
                              ]}
                              valuePropName="checked"
                              label="Amt in Words"
                            >
                              <Switch />
                            </Form.Item>
                          </Col>
                        </Row>
                      </Card>
                    </div>
                  ),
                },
              ]}
            />
          </Form>
        ) : (
          <div style={{ textAlign: "center", marginTop: 100, color: "#ccc" }}>
            {loading ? <Spin /> : "Select a Template to Edit"}
          </div>
        )}
      </Col>
    </Row>
  );
};

export default BillingTemplateEditor;
